### ISSUE TITLE
Create Ember CLI addon

### ISSUE THREAD

**Issue by Ghostavio** [clintjhill/ember-parse-adapter#31]
This is already an awesome adapter, and it would be cool to have an ember-cli addon as they released this feature recently and it significantly reduces installation time. Is this in the roadmap?

Thanks :)

**Comment by mixonic** [comment]
@notmessenger and I talked about his progress building an addon at EmberConf!

**Comment by notmessenger** [comment]
I should be able to get a pull request submitted this weekend.

**Comment by notmessenger** [comment]
https://github.com/clintjhill/ember-parse-adapter/pull/53 is the pull request converting this adapter to Ember CLI 0.1.15.  Once I fix a failing test I will make a pull request to convert to 0.2.0-beta.1

**Comment by notmessenger** [comment]
https://github.com/clintjhill/ember-parse-adapter/pull/54 superseded https://github.com/clintjhill/ember-parse-adapter/pull/53 and has been merged.

**Comment by Ghostavio** [comment]
now it just needs to be published on NPM and have the documentation on the readme file updated and we can close this :)

**Comment by notmessenger** [comment]
@Ghostavio https://github.com/clintjhill/ember-parse-adapter/issues/56 is the request for this
