### ISSUE TITLE
Custom find queries.

### ISSUE THREAD

**Issue by omairvaiyani** [clintjhill/ember-parse-adapter#39]
There doesn't seem to be any obvious way to make a custom where query. 

I had a guess and tried the following but it didn't work:

``` JavaScript
var test = this.modelFor('test');
var questions = this.store.find('question', {where: {test: test} });
```

Any ideas? Is there a wiki?

**Comment by QuantumInformation** [comment]
@omairvaiyani or @mixonic  how would you get the adaptor to return the list of users? I tried  `this.get('store').find('user')` but the adapter made a call to `https://api.parse.com/1/classes/User` instead of `https://api.parse.com/1/users`

**Comment by omairvaiyani** [comment]
I believe you have to do ```this.get('store').find('parse-user')```

See if that works otherwise I'll take a look further.

**Comment by QuantumInformation** [comment]
@omairvaiyani that just returns the current logged in user..

**Comment by QuantumInformation** [comment]
I wonder why the model is called parse-user anyway, why not use user/User like it is on parse.com?

**Comment by omairvaiyani** [comment]
If that's at least returning the current user, it means that the API call is working. Check your Parse data browser to see if other users can be seen (ACLs) by the current user. 

I'm not sure what the reasoning behind using "parse-user" was as I haven't contributed to the code. However, the adapter does take "parse-user" and uses it to adjust the API call accordingly. 

I'm currently away on holiday but I can help you further when I can.

**Comment by QuantumInformation** [comment]
Ah its a special class.

They query that is made is:

https://api.parse.com/1/classes/ParseUser

which is a local representation of user data that can be saved and retrieved from the Parse cloud.

https://parse.com/docs/android/api/com/parse/ParseUser.html

**Comment by QuantumInformation** [comment]
Well currently anyone should be able to see other users, so I'm still trying to figure out what query I need.

![image](https://cloud.githubusercontent.com/assets/216566/8020350/f4b25fb0-0c7d-11e5-9aea-cd06eea95cbd.png)
