### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by QuantumInformation** [clintjhill/ember-parse-adapter#52]
Hi, can we publish this over npm?

**Comment by oriSomething** [comment]
it would be really nice + ember-cli plugin

**Comment by mixonic** [comment]
Yeah. Closing in favor of https://github.com/clintjhill/ember-parse-adapter/issues/31

**Comment by QuantumInformation** [comment]
Why was this closed? Ember addons are published over npm.

**Comment by oriSomething** [comment]
@QuantumInformation  it's closed, exactly because what you said: "*Ember addons are published over npm.*"

**Comment by QuantumInformation** [comment]
I've tried to install it but the addon is not found.

On Tuesday, 17 March 2015, ori livni <notifications@github.com> wrote:

> @QuantumInformation <https://github.com/QuantumInformation> it's closed,
> exactly because what you said: "*Ember addons are published over npm.*"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clintjhill/ember-parse-adapter/issues/52#issuecomment-82609265>
> .
>


-- 

Kind regards
Nikos
