### ISSUE TITLE
RFC: Move to ember-parse organization

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#79]
In #69, the session service was brought up, and I think it would be helpful to have other packages besides just the adapter that offer functionality around Parse. For instance, I would argue that file uploads don't really belong in this repo, and probably neither does the user model, since those are separate concerns from an ember-data adapter. I would propose that this project be moved to an organization on GitHub, and that functionality other than the actual ember-data adapter be moved to separate libraries. This would also provide a logical location for a repo for RFCs.

**Comment by joshfester** [comment]
I would love to see this centralized in a new org. There are a lot of gaps to fill between Ember and Parse. A central location would be very helpful. Hopefully it would encourage more development as well.

**Comment by gcollazo** [comment]
Like the idea of centralizing the work on a new org.

**Comment by QuantumInformation** [comment]
I've even using ember parse, it works great.

-- 

Kind regards
Nikos

**Comment by jacobthemyth** [comment]
@QuantumInformation this would be different from https://github.com/GetBlimp/ember-parse, rather it would be a new organization.

**Comment by mixonic** [comment]
I'm happy to open up a new organization, but I also feel that does not come close to addressing the major priorities of this addon. There is major work to be done on continued improvement to the testing and documentation.

**Comment by mixonic** [comment]
If this is a high priority for you @jacobthemyth, I'd like to see some more thoughts on motivation and on a proposed restructuring (what addons will exist, what are their responsibilities, what can they be extracted from).

**Comment by clintjhill** [comment]
First I agree with @mixonic about the testing and documentation. That would be my priority too. I wanted as well to provide some context to the existence of this project in the first place. It was my intention that this was a "parse app" development library, just as the Parse JS SDK is intended. As such it would require user models, session and some of the other things that are mentioned here as being separated. 

To be clear: I'm in no way against the org idea. I'm simply hesitant to break this all apart from it's original intention.

I'm very open to thoughts about this.

**Comment by joshfester** [comment]
My opinion is that the goal should definitely be to have all the functionality of the Parse JS SDK. However, I think the "ember way" of accomplishing this would be to break things out into separate addons. Off the top of my head, here's some ember-parse addons I would be using at my company:

* ember-data adapter
* ember-cli-deploy-parse
* ember-parse-cloud
* ember-simple-auth-parse
* ember-parse-analytics

I would love to see an ember-parse-cloud addon that works like [ember-api-actions](https://github.com/truenorth/ember-api-actions) for Cloud Functions. Authentication and session management is something that can (and IMO, should) be handled by something outside of ember-data.

To me the grey area is things like ACL's and the special "Parse" models (User, File, Geopoint, etc). I would be fine with these things staying in the ember-data adapter, as they are specifically tied to Parse data, and would stay the same across all ember-parse projects.

The ember-parse org would be an ecosystem that provides all the functionality of the Parse JS SDK. It would allow developers to incrementally add features to their projects, come up with homegrown solutions for specific use-cases (without having to choose between bloat vs re-inventing the wheel), migrate to Parse from other backends, and (perhaps most importantly) contribute to the ember-parse ecosystem without being intimidated by a large monolithic library.
