### ISSUE TITLE
RFC: Versioning

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#80]
Splitting out the discussion from #69, I propose that this library move to the same versioning system as ember and ember-data, which is to say that it should have the same version number as the version of ember-data + ember that it is compatible with. For instance, the current version could/should be `1.0.0-beta.15`.

**Comment by jacobthemyth** [comment]
And just for the record, I am aware #56 already exists, but this is actually a separate question.

**Comment by mixonic** [comment]
I disagree with this for now. The Ember and Ember-Data versioning implies a level of stability this library has not yet reached.

**Comment by jacobthemyth** [comment]
:+1:
