### ISSUE TITLE
Use JavaScript Key instead of the REST API Key

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#81]
For security reasons, the REST API key should not be used on the client side.

Splitting out issue from #69. Relevant comments at 
- https://github.com/clintjhill/ember-parse-adapter/issues/69#issue-71361322
- https://github.com/clintjhill/ember-parse-adapter/issues/69#issuecomment-97933554

**Comment by gcollazo** [comment]
I already did this work. It would be great if someone had the time to review it. Also like the idea of centralizing the work on a new org.

**Comment by joshfester** [comment]
I would love to see this centralized in a new org. There are a lot of gaps to fill between Ember and Parse. A central location would be very helpful. Hopefully it would encourage more development as well.

**Comment by jacobthemyth** [comment]
@gcollazo Please open a pull request for code review, and please comment about the new org on the respective issue #79 so that all the information and opinions about that particular topic can be put in one place.

**Comment by jacobthemyth** [comment]
@joshfester please put those comments in the respective issue #79 so that all the information and opinions about that particular topic can be put in one place. This issue is about using the REST API key.

**Comment by joshfester** [comment]
@jacobthemyth Ah, my bad. So many notifications today. I thought I was on #79

**Comment by jacobthemyth** [comment]
@joshfester :) sorry, I got a little carried away with the issues.

**Comment by gcollazo** [comment]
@jacobthemyth I just opened PR #85 importing all the changed I've made.

**Comment by gcollazo** [comment]
Parse recently launched a new feature that will allow developers to disable REST Push.

This issue can be closed in favor of PR #91 or any other proposal that clearly documents the security risks of having REST Push enabled and a how-to disable guide.

**Comment by gcollazo** [comment]
Ups! missed it was already closed :\

**Comment by jacobthemyth** [comment]
:+1:
