### ISSUE TITLE
RFC: Use separate libraries for anything not specifically part of the ember-data adapter/serializer.

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#82]
There has been discussion in #69 about having some authentication, ACL, session, etc. logic in this library, but I propose that these all be maintained as separate libraries. For instance, I like using ember-simple-auth, and would not like auth logic in this library. This is also related to #79, in that having an ember-parse organization would facilitate this idea.

**Comment by joshfester** [comment]
+1 for this. I really enjoy using ember-simple-auth. Authentication and session management is beyond the scope of an ember-data adapter. However, in my mind ACL functionality is not beyond the scope. It is heavily tied to the adapter and for security reasons it should almost always be used with any Parse objects.

**Comment by QuantumInformation** [comment]
I switched all my logic to use the internal auth in ember parse. Works for
me. I was using simple auth before.

-- 

Kind regards
Nikos

**Comment by jacobthemyth** [comment]
@QuantumInformation this is a separate project from GetBlimp/ember-parse, so that project may continue to do something different. Maybe it would be possible to extract the auth code from that project as a separate repository.

**Comment by joshfester** [comment]
Is anyone else making use of Parse Cloud Functions? To me this is something that falls within the scope of the Data Adapter. However, I have not come up with any solutions that feel right.

**Comment by jacobthemyth** [comment]
@joshfester I would say that it should be a separate library. But yes, I use them extensively in my apps. There might need to be some unified configuration so that, say ember-parse-adapter and ember-parse-cloud could just use the same app id and key, but IMHO, I don't think Cloud Code fits into the ember-data paradigm since ember-data is specifically for data persistence.

Although, on the other hand, are you using Cloud stuff for data persistence? If so, what are the use cases that preclude the use of regular Parse classes? If using cloud functions is necessary for data persistence, I could see it being part of the same library.

**Comment by gcollazo** [comment]
getblimp/ember-parse has a cloud code service you can inject on routes and components. It currently uses the adapter and serializer to communicate.

**Comment by joshfester** [comment]
@jacobthemyth I use Cloud functions indirectly for data persistence. I have a lot of functions that communicate with other services like Stripe, then Parse data gets updated via webhooks.

@gcollazo I really like the way they use the cloud service. That was the inspiration for my current implementation

I guess it's very true that Cloud Functions don't fit the paradigm. Perhaps it could be a separate addon that extends the adapter and creates a service similar to getblimp/ember-parse

**Comment by mixonic** [comment]
Agreed, would love for the session stuff to not be part of the adapter now that there are robust alternatives for session management.
