### ISSUE TITLE
Write integration tests using ajax mocking

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#83]
I think a good way to increase the test coverage of this library would be to basically mock out the whole Parse REST API using ember-cli http-mock endpoints. I going to start working on this, but don't have access to assign this issue to myself.

**Comment by mixonic** [comment]
@jacobthemyth the assignee system is limited to contributors in github. Just a limitation of the platform.

**Comment by jacobthemyth** [comment]
@mixonic ah, didn't know that. Feel free to close this issue if you want. I'll keep the pull request #88 open while I work on it, but I'm not sure if you want to keep open issues with redundant pull requests.
