### ISSUE TITLE
RFC: Create milestones and organize issues

### ISSUE THREAD

**Issue by jacobthemyth** [clintjhill/ember-parse-adapter#84]
I'm trying to spend some time working on open issues here, but it doesn't seem like the issues are very well curated. @notmessenger, could you create issues and milestones detailing the work you mentioned in #69 about getting the library up to date? I would love to help with that effort, as I should have some free time in the upcoming weeks. In addition, it would be great if someone with access could clean up some of these issues. For example, #31 should have been closed a long time ago. I would be more than willing to fulfill sort of a project manager role and organize things and keep things rolling, if the core team thinks this would be helpful.

**Comment by mixonic** [comment]
@jacobthemyth I'm happy to make anyone a collaborator on this repo who consistently delivers quality tested code or leads with great communication. You often find me on the community slack if you want a hand.

As far as milestones and issues tags, what are your thoughts?

**Comment by jacobthemyth** [comment]
@mixonic I had never noticed the community slack channel, I'm on Slack all day for work, so that's great.

I didn't mean to be overly aggressive with my issues and everything this weekend. I would love to contribute, and plan on doing so through quality, tested pull requests. I can be a little verbose, I like to write things out, which has its pros and cons.

My thoughts on milestones would be to have goals for getting compliant with various versions of ember-data:
- 1.0.0-beta.15 (or some other name) would be a milestone for establishing tests and stability on the current codebase, without any additional features or changes. There are a few open issues (e.g. #49) that would seem to be a good fit for this.
- 1.0.0-beta.19.2 (or some other name) would be a milestone to add changes that are new, but still allow for deprecated behavior like `store.push` inside an adapter, non JSON-API payload, etc. (e.g. maybe #15? I haven't looked that closely at it). This would also include a documentation push, as it doesn't seem right to be 1.0 without great documentation.
- 1.0 would be a milestone to close any known bugs and bring the library up to date with ember 2.0 and ember-data 1.13/2.0, including removing deprecated behavior and moving to JSON-API.

**Comment by jacobthemyth** [comment]
Still thinking about tags, I'll post on that tomorrow...

**Comment by mixonic** [comment]
I'm definitely not crazy about going 1.0. This codebase is nowhere near 1.0 ready, sad to say. We could make a milestone for 0.6.0?

**Comment by QuantumInformation** [comment]
0.6 is good for me.
